### ISSUE TITLE
How can I compile or render .twig template directly from variable?

### ISSUE THREAD

**Issue by rafcio21** [jarednova/timber#610]
How can I compile or render .twig template directly from variable?

I know how to do it in Twig, but I have no idea how to rewrite it into timber. I'd love to use it in wordpress pages. Twig solution below:
```
$twig = new \Twig_Environment(new \Twig_Loader_String());
return $rendered = $twig->render(
  "<title>{{ site.name }}</title>",
  array('site' => $site)
);
```

**Comment by jarednova** [comment]
I believe it's as simple as....

```php
$template = get_field('twig_template') // returns my-template.twig
Timber::render($template, array('site' => $site));
```

I recommend passing the default `$context` to each template as it contains data on the site, theme, etc...

```php
$context = Timber::get_context();
$template = get_field('twig_template') // returns my-template.twig
Timber::render($template, $context);
```

```twig
<title>{{ site.name }}</title>
```

**Comment by rafcio21** [comment]
This way it works:
$context = Timber::get_context();
$template = get_field('twig_template'); // returns my-template.twig
Timber::render("single.twig", $context);

When I try to do it your way, it shows nothing.

**Comment by rafcio21** [comment]
Wait, actually it shows sth:
```
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "{% if 1==1 %} &lt;br&gt;... Works, You&#039;re here {{ site.get_template_directory() }} ... {% endif %}" (looked into: C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\plugins\est, C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\themes\twentyfifteen, ).' in C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\Loader\Filesystem.php:195 Stack trace: #0 C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\Loader\Filesystem.php(138): Twig_Loader_Filesystem->findTemplate('{% if 1==1 %}\r\n...') #1 C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\plugins\timber-library\lib\timber-loader.php(64): Twig_Loader_Filesystem->getCacheKey('{% if 1==1 %}\r\n...') #2 C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\plugins\ti in C:\praca\xampp-portable-win32-5.6.8-0-VC11\xampp\htdocs\est\wp-content\plugins\timber-library\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 195
```

**Comment by rafcio21** [comment]
I changed first comment code, so now it is explained more plainly.

**Comment by jarednova** [comment]
Ahhh, I gotcha. In that case you want `Timber::render_string`, check it out here in the docs:

https://github.com/jarednova/timber/wiki/Timber-docs#render_string
